# Generated by Django 5.2.6 on 2025-12-08 14:08

import apps.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=apps.utils.storage.product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=models.ImageField(upload_to=apps.utils.storage.variant_image_upload_path),
        ),
    ]
