# Generated by Django 5.2.6 on 2026-01-08 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantimage',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant'),
        ),
    ]
