# Generated by Django 5.2.6 on 2026-01-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_variantimage_product_variant'),
        ('products', '0003_productreview'),
    ]

    operations = [
    ]
