# Generated by Django 5.2.6 on 2025-12-09 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Conclu�do'), ('CANCELLED', 'Cancelado')], default='PENDING'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('order_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buys', to='orders.order')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buys', to='products.productvariant')),
            ],
            options={
                'db_table': 'order_products',
            },
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
