# Generated by Django 5.2.6 on 2026-01-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='type',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
