# Generated by Django 5.2.6 on 2025-12-12 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_type_orderproduct_delete_buy'),
        ('products', '0003_alter_product_image_alter_variantimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='products.productvariant'),
        ),
    ]
