# Generated by Django 5.2.6 on 2026-01-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
