# Generated by Django 5.2.6 on 2025-12-08 14:08

import apps.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='no_image.png', upload_to=apps.utils.storage.profile_image_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
