# Generated by Django 5.2.6 on 2026-01-20 23:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_message_options_alter_chat_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('client', 'artisan')},
        ),
    ]
