# Generated by Django 5.2.6 on 2025-11-14 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='accounts.users')),
            ],
            options={
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='StoreImages',
            fields=[
                ('store_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.stores')),
            ],
            options={
                'db_table': 'store_images',
            },
        ),
        migrations.CreateModel(
            name='StoreCategories',
            fields=[
                ('store_categories_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categories')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_categories', to='stores.stores')),
            ],
            options={
                'db_table': 'store_categories',
                'unique_together': {('category', 'store')},
            },
        ),
    ]
