# Generated by Django 5.2.6 on 2025-12-15 18:21

import apps.utils.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to=apps.utils.storage.store_image_upload_path)),
                ('banner', models.ImageField(upload_to=apps.utils.storage.banner_upload_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('store_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.utils.storage.store_gallery_upload_path)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
            options={
                'db_table': 'store_images',
            },
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('store_categories_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_categories', to='core.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_categories', to='stores.store')),
            ],
            options={
                'db_table': 'store_categories',
                'unique_together': {('category', 'store')},
            },
        ),
    ]
