# Generated by Django 5.2.6 on 2025-12-08 14:08

import apps.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='banner',
            field=models.ImageField(upload_to=apps.utils.storage.banner_upload_path),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(upload_to=apps.utils.storage.store_image_upload_path),
        ),
        migrations.AlterField(
            model_name='storeimage',
            name='image',
            field=models.ImageField(upload_to=apps.utils.storage.store_gallery_upload_path),
        ),
    ]
