# Generated by Django 5.2.6 on 2026-01-10 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_date_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storecategory',
            old_name='store_categories_id',
            new_name='store_category_id',
        ),
        migrations.AlterUniqueTogether(
            name='storecategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='stores.storecategory'),
        ),
        migrations.AddField(
            model_name='storecategory',
            name='name',
            field=models.CharField(default='Geral', max_length=150),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='storecategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='storecategory',
            name='store',
        ),
    ]
