# Generated by Django 5.2.6 on 2026-01-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_rename_store_categories_id_storecategory_store_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
